name: "Comment Progress"
inputs:
  comment_id:
    description: 'The ID of the comment to update'
    required: false
  complete_nuget:
    description: 'completes the nuget step, the value must be a string containing the url to the artifact'
    required: false
  complete_core_tests:
    description: 'completes the core tests step, the value must be a string containing "success" if succeeded'
    required: false
  complete_win_tests:
    description: 'completes the windows tests step, the value must be a string containing "success" if succeeded'
    required: false
  complete_linux_tests:
    description: 'completes the linux tests step, the value must be a string containing "success" if succeeded'
    required: false
  complete_mac_tests:
    description: 'completes the macos/catalyst tests step, the value must be a string containing "success" if succeeded'
    required: false
  complete_android_tests:
    description: 'completes the android tests step, the value must be a string containing "success" if succeeded'
    required: false
  complete_ios_tests:
    description: 'completes the ios tests step, the value must be a string containing "success" if succeeded'
    required: false
outputs: 
  comment_id: 
    description: "ID of the comment" 
    value: ${{ steps.update-comment.outputs.comment_id }}
runs:
  using: "composite"
  steps:
    - id: update-comment
      uses: actions/github-script@v8
      with:
        script: |
          const runId = "${{ github.run_id }}";
          const commentId = "${{ inputs.comment_id }}";
          const nugetUrl = "${{ inputs.complete_nuget }}";          
          const coreTestsStatus = "${{ inputs.complete_core_tests }}";
          const winTestsStatus = "${{ inputs.complete_win_tests }}";
          const linuxTestsStatus = "${{ inputs.complete_linux_tests }}";
          const macTestsStatus = "${{ inputs.complete_mac_tests }}";
          const androidTestsStatus = "${{ inputs.complete_android_tests }}";
          const iosTestsStatus = "${{ inputs.complete_ios_tests }}";

          if (!commentId) {
            let firstBody = `One moment, checks are running... 🕰️👀
            
            - [ ] Create NuGet packages
            - [ ] Test core packages
            - [ ] Test UI packages on Linux
            - [ ] Test UI packages on Windows
            - [ ] Test UI packages on MacOs/Catalyst
            - [ ] Test UI packages on Android
            - [ ] Test UI packages on iOS
            `;

            const newComment = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: firstBody
            });

            core.setOutput("comment_id", newComment.data.id);

            return;
          }

          const comment = await github.rest.issues.getComment({ 
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: commentId
          });
          
          let body = comment.data.body;

          if (nugetUrl) {
            body = body.replace(
              "- [ ] Create NuGet packages", 
              `- [x] ~~Create NuGet packages~~. While these changes are approved and published to the NuGet Gallery, you can [download](${nugetUrl}) and install these packages locally. If you need help to do so, check out [this guide](https://stackoverflow.com/questions/10240029/how-do-i-install-a-nuget-package-nupkg-file-locally-to-visual-studio) article.`);
          }

          if (coreTestsStatus) {
            if (coreTestsStatus == "success") {
              body = body.replace(
                "- [ ] Test core packages", 
                `- [x] ~~Test core packages~~ ✅ [succeeded](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            } else {
              body = body.replace(
                "- [ ] Test core packages", 
                `- [x] ~~Test core packages~~ ❌ [failed](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            }
          }

          if (winTestsStatus) {
            if (winTestsStatus == "success") {
              body = body.replace(
                "- [ ] Test UI packages on Windows", 
                `- [x] ~~Test UI packages on Windows~~ ✅ [succeeded](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId`})`);
            } else {
              body = body.replace(
                "- [ ] Test UI packages on Windows", 
                `- [x] ~~Test UI packages on Windows~~ ❌ [failed](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            }
          }

          if (linuxTestsStatus) {
            if (linuxTestsStatus == "success") {
              body = body.replace(
                "- [ ] Test UI packages on Linux", 
                `- [x] ~~Test UI packages on Linux~~ ✅ [succeeded](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            } else {
              body = body.replace(
                "- [ ] Test UI packages on Linux", 
                `- [x] ~~Test UI packages on Linux~~ ❌ [failed](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            }
          }

          if (macTestsStatus) {
            if (macTestsStatus == "success") {
              body = body.replace(
                "- [ ] Test UI packages on MacOs/Catalyst", 
                `- [x] ~~Test UI packages on MacOs/Catalyst~~ ✅ [succeeded](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            } else {
              body = body.replace(
                "- [ ] Test UI packages on MacOs/Catalyst", 
                `- [x] ~~Test UI packages on MacOs/Catalyst~~ ❌ [failed](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            }
          }

          if (androidTestsStatus) {
            if (androidTestsStatus == "success") {
              body = body.replace(
                "- [ ] Test UI packages on Android", 
                `- [x] ~~Test UI packages on Android~~ ✅ [succeeded](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            } else {
              body = body.replace(
                "- [ ] Test UI packages on Android", 
                `- [x] ~~Test UI packages on Android~~ ❌ [failed](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            }
          }

          if (iosTestsStatus) {
            if (iosTestsStatus == "success") {
              body = body.replace(
                "- [ ] Testing UI packages on iOS ⏳...", 
                `- [x] ~~Testing UI packages on iOS~~ ✅ [succeeded](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            } else {
              body = body.replace(
                "- [ ] Testing UI packages on iOS ⏳...", 
                `- [x] ~~Testing UI packages on iOS~~ ❌ [failed](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`);
            }
          }

          await github.rest.issues.updateComment({
            comment_id: commentId,
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body });