name: "Comment Progress"
inputs:
  comment_id:
    description: 'The ID of the comment to update'
    required: false
  complete_nuget:
    description: 'completes the nuget step, the value must be a string containing the url to the artifact'
    required: false
  complete_tests:
    description: 'completes the specified tests, options are core, windows, linux, mac, android, ios'
    required: false
  test_status:
    description: 'a string indicating "status passedCount failedCount", status can be "success" or "failure", passedCount and failedCount are integers'
    required: false
outputs: 
  comment_id: 
    description: "ID of the comment" 
    value: ${{ steps.update-comment.outputs.comment_id }}
runs:
  using: "composite"
  steps:
    - id: update-comment
      uses: actions/github-script@v8
      with:
        script: |
          const runId = "${{ github.run_id }}";
          const commentId = "${{ inputs.comment_id }}";
          const nugetUrl = "${{ inputs.complete_nuget }}";
          const completeTests = "${{ inputs.complete_tests }}";
          const testStatusInput = "${{ inputs.test_status }}";

          let testStatus = null;
          let succeededTests = 0;
          let failedTests = 0;

          if (testStatusInput) {
            const parts = testStatusInput.split(" ");
            testStatus = parts[0];
            succeededTests = parts[1];
            failedTests = parts[2];
          }

          if (!commentId) {
            let firstBody = `Thanks for your contribution! 👌☺️ We need to verify and run tests for your changes. Progress will be updated here:
            
            - [ ] Create NuGet packages
            - [ ] Test core packages
            - [ ] Test UI packages on Linux
            - [ ] Test UI packages on Windows
            - [ ] Test UI packages on MacOs/Catalyst
            - [ ] Test UI packages on Android
            - [ ] Test UI packages on iOS
            `;

            const newComment = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: firstBody
            });

            core.setOutput("comment_id", newComment.data.id);

            return;
          }

          const comment = await github.rest.issues.getComment({ 
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: commentId
          });
          
          let body = comment.data.body;

          if (nugetUrl) {
            body = body.replace(
              "- [ ] Create NuGet packages", 
              `- [x] ~~Create NuGet packages~~. While these changes are approved and published to the NuGet Gallery, you can [download](${nugetUrl}) and install these packages locally. If you need help to do so, check out [this guide](https://stackoverflow.com/questions/10240029/how-do-i-install-a-nuget-package-nupkg-file-locally-to-visual-studio) article.`);
          }

          let statusString = testStatus == "success" 
            ? `✅ [${succeededTests} tests succeeded](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`
            : `❌ [${failedTests}/${succeededTests + failedTests} tests failed](https://github.com/Live-Charts/LiveCharts2/actions/runs/${runId})`;

          if (completeTests == "core") {
            body = body.replace(
              "- [ ] Test core packages", 
              `- [x] ~~Test core packages~~ ${statusString}`);
          }

          if (completeTests == "linux") {
            body = body.replace(
              "- [ ] Test UI packages on Linux", 
              `- [x] ~~Test UI packages on Linux~~ ${statusString}`);
          }
          
          if (completeTests == "windows") {
            body = body.replace(
              "- [ ] Test UI packages on Windows", 
              `- [x] ~~Test UI packages on Windows~~ ${statusString}`);
          }

          if (completeTests == "mac") {
            body = body.replace(
              "- [ ] Test UI packages on MacOs/Catalyst", 
              `- [x] ~~Test UI packages on MacOs/Catalyst~~ ${statusString}`);
          }

          if (completeTests == "android") {
            body = body.replace(
              "- [ ] Test UI packages on Android", 
              `- [x] ~~Test UI packages on Android~~ ${statusString}`);
          }

          if (completeTests == "ios") {
            body = body.replace(
              "- [ ] Test UI packages on iOS", 
              `- [x] ~~Test UI packages on iOS~~ ${statusString}`);
          }

          await github.rest.issues.updateComment({
            comment_id: commentId,
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body });