name: LiveCharts

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build-packages: 
    runs-on: windows-2025    
    strategy:
      matrix:
        include:
          - project: src/LiveChartsCore
            short-name: core
          - project: src/skiasharp/LiveChartsCore.SkiaSharp
            short-name: skiasharp
    steps: 
      - name: Checkout 
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0 # important for deterministic builds?
      
      - name: Setup .NET 
        uses: actions/setup-dotnet@v5.0.1
        with: 
          dotnet-version: '10.0.100'
      
      - name: Pack
        run: dotnet pack ${{ matrix.project }} -c Release -o artifacts /p:IsPacking=true /p:LiveChartsVersionSurfix=-${{ github.sha }}
        
      - name: Publish
        run: dotnet nuget push **/*.nupkg --source "https://nuget.pkg.github.com/beto-rodriguez/index.json" --api-key ${{ secrets.GH_TOKEN }}

      - name: Upload test results
        id: upload
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.short-name }}-package
          path: "**/*.nupkg"

  comment-packages-link:
    runs-on: ubuntu-24.04
    needs: build-packages
    permissions: 
      issues: write 
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v7.0.0
        with:
          path: collected

      - name: Flatten packages 
        run: | 
          mkdir -p flat 
          find collected -type f -name '*.nupkg' -exec cp {} flat/ \;

      - id: upload
        uses: actions/upload-artifact@v6.0.0 
        with:
          name: livecharts-${{ github.sha }}
          path: flat/**/*.nupkg

      - uses: actions/github-script@v8
        with:
          script: |
            let body = `NuGet packages built successfully! 🥳
            
            You can download the NuGet packages with these changes [here](${process.env.ARTIFACT_URL}).
            
            While these changes are approved and published to the NuGet Gallery, you can install these packages locally. 
            If you need help to do so, check out [this guide](https://stackoverflow.com/questions/10240029/how-do-i-install-a-nuget-package-nupkg-file-locally-to-visual-studio) article.`;
              
            await github.rest.issues.createComment({
              issue_number: context.issue.number, 
              owner: context.repo.owner, 
              repo: context.repo.repo, 
              body
            });
        env: 
          ARTIFACT_URL: ${{ steps.upload.outputs.artifact-url }}

  run-tests:
    runs-on: windows-2025
    needs: build-packages
    strategy:
      matrix:
        framework: [ net8.0, net462 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: '10.0.100'

      - name: Run unit tests
        run: dotnet run --project tests/CoreTests/CoreTests.csproj -f ${{ matrix.framework }} --report-trx -p:UseNuGetPackages=true -p:LiveChartsVersionSurfix=-${{ github.sha }}

      - name: Upload test results
        uses: actions/upload-artifact@v6.0.0
        with:
          name: test-results-${{ matrix.framework }}
          path: "**/*.trx"

  comment-test-results:
    runs-on: ubuntu-24.04
    needs: run-tests
    permissions:
      contents: read
      actions: read
      checks: write
      issues: write 
      pull-requests: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v6.0.1

      - name: Download artifacts
        uses: actions/download-artifact@v7.0.0
        with:
          path: artifacts

      - name: Publish results
        id: report
        uses: dorny/test-reporter@v2.4.0
        with:
          name: test-results
          path: "artifacts/**/*.trx"
          reporter: dotnet-trx

      - name: Comment results
        uses: actions/github-script@v8
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const body = `## 🧪 Test Results
            - **Conclusion:** ${{ steps.report.outputs.conclusion }}
            - ✅ Passed: ${{ steps.report.outputs.passed }}
            - ❌ Failed: ${{ steps.report.outputs.failed }}
            - ⚠️ Skipped: ${{ steps.report.outputs.skipped }}
            - ⏱️ Time: ${{ steps.report.outputs.time }} ms
            - 🔗 [Check Run Details](${process.env.URL_HTML}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });

        env: 
          URL_HTML: ${{ steps.report.outputs.url_html }}