name: Core Unit Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build-packages: 
    runs-on: windows-2025    
    strategy:
      matrix:
        include: 
          - project: src/LiveChartsCore 
            shortName: core
          - project: src/skiasharp/LiveChartsCore.SkiaSharp
            shortName: skiaSharp
    steps: 
      - name: Checkout 
        uses: actions/checkout@v6.0.1
      
      - name: Setup .NET 
        uses: actions/setup-dotnet@v5.0.1
        with: 
          dotnet-version: '10.0.100'
      
      - name: Pack
        run: dotnet pack ${{ matrix.project }} -c Release -o artifacts /p:IsPacking=true /p:LiveChartsVersionSurfix=-${{ github.sha }}
        
      - name: Publish
        run: dotnet nuget push **/*.nupkg --source "https://nuget.pkg.github.com/beto-rodriguez/index.json" --api-key ${{ secrets.GH_TOKEN }}

      - name: Upload test results
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.shortName }}-package-${{ github.sha }}
          path: "**/*.nupkg"          

  comment-packages:
    runs-on: windows-2025
    needs: build-packages
    permissions: 
      issues: write 
      pull-requests: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v6.0.1

      - name: Comment with artifact link
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ NuGet packages built for commit ${{ github.sha }} 👉 [Download artifacts here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`
            })

  run-tests:
    runs-on: windows-2025
    needs: build-packages
    strategy:
      matrix:
        framework: [ net8.0, net462 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: '10.0.100'

      - name: Run unit tests
        run: dotnet run --project tests/CoreTests/CoreTests.csproj -f ${{ matrix.framework }} --report-trx -p:UseNuGetPackages=true -p:LiveChartsVersionSurfix=-${{ github.sha }}

      - name: Upload test results
        uses: actions/upload-artifact@v6.0.0
        with:
          name: test-results-${{ matrix.framework }}
          path: "**/*.trx"

  publish:
    runs-on: ubuntu-24.04
    needs: run-tests
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v7.0.0
        with:
          path: artifacts

      - name: Publish results
        uses: dorny/test-reporter@v2.4.0
        with:
          name: test-results
          path: "artifacts/**/*.trx"
          reporter: dotnet-trx